# Generated by Django 4.2.7 on 2026-02-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(help_text='Name of the person requesting leave', max_length=200)),
                ('start_date', models.DateField(help_text='Start date of the leave period')),
                ('end_date', models.DateField(help_text='End date of the leave period')),
                ('leave_type', models.CharField(choices=[('normal', 'Normal Leave'), ('sick', 'Sick Leave')], default='normal', help_text='Type of leave being requested', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
